version: '3.9'

services:
  jupyter:
    container_name: jupyter
    hostname: jupyter
    build:
      context: ./gpt_service
    ports:
      - '8888:8888'
    volumes:
      - ./code:/code/
    networks:
      - my-api-net

networks:
  my-api-net: # Define the custom network
    driver: bridge
